PORT=9002
DB_DRIVER=pg
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=123zhangbei
DB_NAME=basic
GATEWAY_SERVICE_URL=http://127.0.0.1:9000
AUTH_SERVICE_URL=http://127.0.0.1:9001
INTERNAL_API_SECRET=mono-repo-internal-dev
DATASOURCE_NOTIFY_PREFIX=mono:service-datasource:
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0
SESSION_PREFIX=mono:session:
CORS_ORIGIN=http://localhost:3000
