/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    ACheckboxGroup: typeof import('antdv-next')['CheckboxGroup']
    ACol: typeof import('antdv-next')['Col']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADrawer: typeof import('antdv-next')['Drawer']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AInputSearch: typeof import('antdv-next')['InputSearch']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AModal: typeof import('antdv-next')['Modal']
    APagination: typeof import('antdv-next')['Pagination']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    ARow: typeof import('antdv-next')['Row']
    ASelect: typeof import('antdv-next')['Select']
    ASelectOption: typeof import('antdv-next')['SelectOption']
    ASpace: typeof import('antdv-next')['Space']
    ASpin: typeof import('antdv-next')['Spin']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
