/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ASpin: typeof import('antdv-next')['Spin']
    ATag: typeof import('antdv-next')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
